[workspace]
members = ["core", "bindings/node", "bindings/android/rust"]
resolver = "2"

[workspace.package]
authors     = ["min.su <sumin1500160640@gmail.com>"]
description = "A Rust implementation of bsdiff and bspatch — multi-platform"
edition     = "2021"
version     = "0.0.6"
license     = "MIT"

[workspace.dependencies]
qbsdiff  = "1.4.4"
tempfile = "3.8"

[profile.release]
lto   = true
strip = "symbols"
