/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 检查文件访问权限 */
export declare function checkFileAccessSync(filePath: string): void

/** JavaScript 压缩比信息结构 */
export interface CompressionRatioJs {
  oldSize: number
  newSize: number
  patchSize: number
  ratio: number
}

export declare function diff(oldStr: string, newStr: string, patch: string): Promise<void>

export declare function diffSync(oldStr: string, newStr: string, patch: string): void

/** 获取压缩比信息 */
export declare function getCompressionRatioSync(oldStr: string, newStr: string, patch: string): CompressionRatioJs

/** 获取文件大小 */
export declare function getFileSizeSync(filePath: string): number

/** 获取补丁文件信息 */
export declare function getPatchInfoSync(patch: string): PatchInfoJs

export declare function patch(oldStr: string, newStr: string, patch: string): Promise<void>

/** JavaScript 补丁信息结构 */
export interface PatchInfoJs {
  size: number
  compressed: boolean
}

export declare function patchSync(oldStr: string, newStr: string, patch: string): void

export declare function verifyPatch(oldStr: string, newStr: string, patch: string): Promise<boolean>

/** 验证补丁文件完整性 */
export declare function verifyPatchSync(oldStr: string, newStr: string, patch: string): boolean
