/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function diff(oldStr: string, newStr: string, patch: string): Promise<void>

export declare function diffSync(oldStr: string, newStr: string, patch: string): void

export declare function patch(oldStr: string, newStr: string, patch: string): Promise<void>

export declare function patchSync(oldStr: string, newStr: string, patch: string): void
